import { StyleSheet } from 'react-native';

const SubjectStyles = StyleSheet.create({
  container: {
    flex: 1, 
    backgroundColor: '#5c6540',
    paddingTop: '10%',
    paddingBottom: '20%',
    paddingLeft:  '5%',
    paddingRight: '5%',
  },
  container2: {
    flex: 1,
    //paddingTop: '%',
    paddingLeft: '10%',
    marginBottom: '4%',
    //alignContent: 'space-between',
    backgroundColor: '#867965',
    borderTopLeftRadius: 7,
    borderTopRightRadius: 7,
    borderBottomLeftRadius: 7,
    borderBottomRightRadius: 7,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 7,
  },
  container3: {
    flex: 0,
    paddingTop: '0%',
    paddingBottom: '3%',
    // paddingLeft:  '5%',
    // paddingRight: '5%',
    backgroundColor: '#484035',
    marginTop: '5%',
    marginLeft: '-11.3%',
    marginBottom: '5%',
    color: 'white',
  },
  container4: {
    backgroundColor: '#867965',
    marginBottom: '-22%',
    marginLeft: '-6%',
    marginRight: '-6%',
  },
  container5: {
    backgroundColor: '#484035',
    marginTop: '2%',
    //marginLeft: '-11.3%',
    marginBottom: '2%',
    //color: 'white',
    flexDirection: 'row',
    //marginHorizontal: 20,
  },
  flist: {
    width: '45%',
    height: '100%',
    marginTop: '10%',
    marginLeft: '5%',
  },
  slist: {
    //padding: -100,
    //alignItems: 'center',
    color: 'white',
    width: '45%',
    height: '100%',
    marginTop: '10%',
    marginRight: '5%',
    //flex: 0,
  },
  flat: {
    backgroundColor: '#484035',
    marginRight: '74%',
    borderTopLeftRadius: 7,
    borderTopRightRadius: 7,
    borderBottomLeftRadius: 7,
    borderBottomRightRadius: 7,
    //flex: 1,
    //paddingTop: 90
  },
  item: {
    color: 'white',
    padding: 20,
    borderColor: 'black',
    borderWidth: 2,
    borderRadius: 10,
  },
  title: {
    marginTop: 10,
    marginLeft: 35,
    //margin: 20,
    fontSize: 28,
    paddingLeft: '25%',
    color: 'white',
    //alignSelf: 'center',
  },
  // for flatlist
  itemContainer: {
    backgroundColor: '#867965',
    overflow: 'hidden',
    borderBottomColor: 'transparent',
    borderTopColor: 'transparent',
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    marginRight: '5%',
  },
  titleContainer: {
    backgroundColor: 'rgba(0, 0, 0, 0.29)',
    padding: 8,
    borderRadius: 10,
    alignItems: 'center',
  },
  title2: {
    fontSize: 14,
    fontWeight: '300',
    color: 'white',
  },
  separator: {
    height: 7,
    backgroundColor: 'transparent',
  },
});

export default SubjectStyles;